server {
	listen 172.21.8.95:80;
	server_name pma.aleksandar.pro;

	return 301 https://$host$request_uri;
}

server {
	listen 172.21.8.95:443 ssl;
	server_name pma.aleksandar.pro;

	ssl_certificate     /path/to/ssl/aleksandar.pro.pem;
	ssl_certificate_key /path/to/ssl/aleksandar.pro.key;

	location / {
		proxy_ssl_server_name on;
		proxy_ssl_name $host;
		proxy_pass https://172.21.8.95:8443;
	}
}
